Allow key override in constructor
azavea/django-amazon-ses pull request #32
Opened 2018-02-27 16:19 UTC by frco9

It allows to use dynamic and multiple SES keys on runtime : 

```
from django.core import mail

aws_ses_access_key = 'my_access_key' # Fetch keys dynamically from secure store
aws_ses_secret_key = 'my_secret_key'
with mail.get_connection(aws_access_key_id=aws_ses_access_key,
                                     aws_secret_access_key=aws_ses_secret_key) as connection:
    mail.EmailMessage(
        subject1, body1, from1, [to1],
        connection=connection,
    ).send()
    mail.EmailMessage(
        subject2, body2, from2, [to2],
        connection=connection,
    ).send()
```

2018-03-10 17:03 UTC, hectcastro requested changes
Hey @frco9, thanks for the PR! I left a few comments to address before we can merge.

2018-03-10 17:03 UTC, hectcastro commented on django_amazon_ses.py
> +        if aws_access_key_id and aws_secret_access_key:
Can these checks please be converted to use `is not None`?

2018-03-10 17:03 UTC, hectcastro commented on .gitignore
> +.vscode/settings.json
We would like to refrain from adding editor specific ignore rules to the repository `.gitignore` file. Can you please add this to your local global `.gitignore` files instead?

2018-03-10 17:03 UTC, hectcastro commented on django_amazon_ses.py
> +
Too many blank lines here for the linter as well.

2018-03-13 14:36 UTC, frco9 commented
@hectcastro It should be better now ?

2018-03-14 16:06 UTC, jjorissen52 commented
This PR results in 
>An error occurred (SignatureDoesNotMatch) when calling the SendRawEmail operation: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

Regardless of whether I have `AWS_ACCESS_KEY_ID` and `AWS_ACCESS_KEY_ID` set.

2018-03-15 15:34 UTC, hectcastro approved these changes

2018-03-15 15:34 UTC, merged